data:
  name: 'Burgers'
  datapath: 'data/testing/burgers.mat'
  offset: 0

test:
  pre-trained: 'pretrained-models/pretrained-burgers.pkl'
  iterations: 2000

generate:
  seed: 0
  device: 'cuda'
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs: 320
  zeta_pde: 100