data:
  name: 'Helmholtz'
  datapath: 'data/testing/helmholtz.mat'
  offset: 0

test:
  pre-trained: 'pretrained-models/pretrained-helmholtz.pkl'
  iterations: 2000

generate:
  seed: 0
  device: 'cuda'
  batch_size: 1
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
  zeta_obs_a: 200
  zeta_obs_u: 30000
  zeta_pde: 1